# Base image
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install app dependencies
RUN yarn install

# Bundle app source
COPY . .

COPY wait-for-it.sh /usr/wait-for-it.sh
RUN chmod +x /usr/wait-for-it.sh

# Copy the .env and .env.development files
# COPY .env .development.env ./

RUN npx prisma generate

# Creates a "dist" folder with the production build
RUN yarn build

# Expose the port on which the app will run
EXPOSE 3000

# Start the server using the development build
CMD ["sh", "-c", "/usr/wait-for-it.sh mysql_db:3306 -- npm run start:migrate:dev"]